@echo off
echo Installing dependencies...
call npm install --legacy-peer-deps
call npm install firebase --legacy-peer-deps
echo Generating Prisma Client...
call npx prisma generate
echo Enabling Web Frameworks...
call firebase experiments:enable webframeworks
echo Deploying to Firebase...
call firebase deploy --only hosting
echo Done!
